sudo: false
language: python
python:
  - 3.5
  - 3.5.2
env:
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
  - FLASK=0.7.2
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
script:
- python database_setup.py test
- python TraashManagementSystem.py test